### ISSUE TITLE
Incorrect cargo capacities

### ISSUE THREAD

**Issue by 2TallTyler** [javelinnl/spacey#1]
Cargo rockets carry a quarter of their intended cargo, due to a quirk of how aircraft are coded in OpenTTD. For rockets with a capacity of 1, this is 1/4 rounded down to 0. 

![rocket_capacity](https://user-images.githubusercontent.com/55058389/100489117-6cbc0100-30e0-11eb-8f0e-63c665e816a2.png)

From the [NML specs](https://newgrf-specs.tt-wiki.net/wiki/NML:Vehicles#Aircraft_properties):

> Capacity for the mail compartment, if refitted to a cargo in the CC_PASSENGERS class. When refitted to other cargoes, this capacity is added to the passenger capacity to determine the base capacity. The actual capacity is set to this base capacity divided by 1 for mail, 2 for goods and 4 for all other cargoes. To override this effect, use the passenger_capacity and mail_capacity callbacks.

My suggestion would be to use the callbacks — just move passenger_capacity and mail_capacity from property {} to graphics {}.

**Comment by javelinnl** [comment]
Thanks! I haven't made any kind of attempt to seriously balance them as viable vehicles yet, but it was indeed my intention to have prototypes carry at least 1 unit. I was already wondering why it behaved that way.
